name: C/C++ CI with conan

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing Conan
        run: |
          make init
      - name: Conan Initialization
        run: |
          make conan_init
      - name: Conan Build
        run: |
          make conan_build
      - name: Debug Virtaul display
        run: |
          sudo apt-get install -y libgl1-mesa-dev xorg-dev xvfb mesa-utils
          sudo Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          # Wait a bit to ensure Xvfb has started
          sleep 30
          glxinfo
          timeout 10s glxgears || true
      - name: Unit Tests
        run: |
          export DISPLAY=:99
          make tests ARGS='-s -r xml'
