name: C/C++ CI with conan

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: gcc:latest
      env: 
        DISPLAY: :99
    steps:
      - uses: actions/checkout@v4
      - name: Installing Conan
        run: |
          apt update
          apt install -y make sudo
          make init
      - name: Conan Initialization
        run: |
          make conan_init
      - name: Conan Build
        run: |
          make conan_build
      - name: Debug Virtaul display
        env:
          DISPLAY_PORT: :99
        run: |
          sudo apt-get install -y libgl1-mesa-dev xorg-dev xvfb mesa-utils
          sudo Xvfb $DISPLAY -screen 0 1024x768x24 &
          # Wait a bit to ensure Xvfb has started
          sleep 30
          glxinfo
          timeout 10s glxgears || true
      - name: Unit Tests
        run: |
          make tests ARGS='-s -r xml'
