name: C/C++ CI with conan

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing Conan
        run: |
          pip install conan
          conan version
      - name: Conan Initialization
        run: |
          conan profile detect
          conan profile show
          conan install . --build=missing
      - name: Conan Build
        run: |
          conan build .
